#!/usr/bin/env python
import requests
from bs4 import BeautifulSoup

def print_list(xs):
    for x in xs:
        print(x)


def parse_rijmwoorden_page(soup):
    active_results = soup.find(class_='results').find(class_='active')
    for section in active_results.find_all(class_=lambda x:x in ['primary','secondary']):
        for link in section.find_all('a'):
            yield link.text


def get_rijmwoorden(woord):
    resp = requests.get(f"https://rijmwoordenboek.vandale.nl/rijm/{woord}")
    soup = BeautifulSoup(resp.text, 'html.parser')
    pages = soup.find(class_='resultspages')
    last_page = int(pages.find_all('span')[-1].text)
    yield from parse_rijmwoorden_page(soup)
    for i in range(2,last_page+1):
        resp = requests.get(f"https://rijmwoordenboek.vandale.nl/rijm/{woord}/{i}")
        soup = BeautifulSoup(resp.text, 'html.parser')
        yield from parse_rijmwoorden_page(soup)


def get_synoniemen(woord):
    resp = requests.get(f"https://synoniemen.net/index.php?zoekterm={woord}")
    soup = BeautifulSoup(resp.text, 'html.parser')
    dl = soup.find(class_="alssynoniemtabel")
    links = dl.find_all('a')
    return [link.text for link in links]


if __name__ == "__main__":
    import argparse
    funcs = {
        "rijmwoorden": get_rijmwoorden,
        "synoniemen": get_synoniemen,
    }
    parser = argparse.ArgumentParser()
    parser.add_argument("type", choices=funcs.keys())
    parser.add_argument("woord")
    args = parser.parse_args()

    words = funcs.get(args.type)(args.woord)
    print_list(words)
