#!/usr/bin/env python
import requests
from bs4 import BeautifulSoup

def print_list(xs):
    for x in xs:
        print(x)

def get_rijmwoorden(woord):
    resp = requests.get(f"https://rijmwoordenboek.vandale.nl/rijm/{woord}")
    soup = BeautifulSoup(resp.text, 'html.parser')
    results = soup.find(class_='results')
    for primary in results.find_all(class_='primary'):
        for link in primary.find_all('a'):
            yield link.text


def get_synoniemen(woord):
    resp = requests.get(f"https://synoniemen.net/index.php?zoekterm={woord}")
    soup = BeautifulSoup(resp.text, 'html.parser')
    dl = soup.find(class_="alssynoniemtabel")
    links = dl.find_all('a')
    return [link.text for link in links]


if __name__ == "__main__":
    import argparse
    funcs = {
        "rijmwoorden": get_rijmwoorden,
        "synoniemen": get_synoniemen,
    }
    parser = argparse.ArgumentParser()
    parser.add_argument("type", choices=funcs.keys())
    parser.add_argument("woord")
    args = parser.parse_args()

    words = funcs.get(args.type)(args.woord)
    print_list(words)
